name: mixpanel_analytics
description:
  A dart wrapper on the mixpanel REST API to be used in Flutter applications.
  As this is using the http REST API it works both with Android and iOS.
version: 1.2.1
author: "Alpha Dev Team <alphahealth-development@telefonica.com>"
homepage: https://github.com/Alpha-health/mixpanel_analytics
repository: https://github.com/Alpha-health/mixpanel_analytics
issue_tracker: https://github.com/Alpha-health/mixpanel_analytics/issues

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: "^2.0.6"
  device_info: "^0.4.1+4"
  http: "^0.12.0+2"
  package_info: ">=0.4.0+13 <2.0.0"
  path: "^1.6.4"
  shared_preferences: "^0.5.6+2"
  sqflite: "^1.1.5"
  uuid: "^2.0.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.0

flutter:
